# AntiAgeExpertTestTask
services:
  mssql:
    container_name: mssqlserver
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    user: root 
    environment:
      SA_PASSWORD: "SuperStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/var/opt/mssql
      - ./init-db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - ./init-db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - usermanagementnetwork

  usermanagementservice:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=AntiAgeExpertTestTask;User Id=sa;Password=SuperStrong!Passw0rd;Connect Timeout=10;Encrypt=True;TrustServerCertificate=True;
    ports:
      - "5066:8080"
    depends_on:
      - mssql
    networks:
      - usermanagementnetwork
    entrypoint: >
      sh -c "/docker-entrypoint-initdb.d/init-db.sh && dotnet UserManagementService.dll"

networks:
  usermanagementnetwork:
    driver: bridge

volumes:
  mssql-data:
